dataset:
  name: baseline-1h-1h
  dataset_module: sacyr
  root: ./data/datasets
  num_workers: 4
  mode: reggresion  # classification
  # kfold:
  #   num_folds: 5
  #   shuffle: True

scaler:
  name: quantil # standard

# preprocessing:
  # - name: to_tensor
  # - name: normalize
  #   mean: [0.5]
  #   std: [0.5]
  # - name: gaussian_blur
  #   kernel_size: 3
  # - name: random_horizontal_flip
  #   probability: 0.5
  # - name: random_crop
  #   padding: 4
  #   size: 32
  #   probability: 0.2


model:
  # name: resnet18
  # weights: ResNet18_Weights.DEFAULT
  # num_classes: 1

  # name: mlp
  # num_layers: 3
  # hidden_size: 512
  # activation: relu
  # dropout: 0.3

  name: periodical_mlp
  num_layers: 3
  hidden_size: 512
  dropout: 0.3
  d_embedding: 64
  n_frequencies: 48
  frequency_init_scale: 5

loss:
  name: mse

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001
  scheduler: step
  step_size: 10
  gamma: 0.1

training:
  epochs: 100
  batch_size: 1024
  num_workers: 2
  prefetch_factor: 3
  seed: 42
  device: cuda
  log_dir: logs

scheduler:
   name: reduce_on_plateau
   patience: 1
   factor: 0.1

metrics:
  # - name: f1_score
  #   average: weighted
  - name: mae


callbacks:
#  - name: early_stopping
#    patience: 5
  - name: checkpoint
    dirpath: "checkpoints/"
    monitor: "Val_loss" # cap-sensitive
    mode: "min"
  - name: wandb_logger
    project: "sacyr"
    entity: "inaki"
  - name: early_stopping
    patience: 3
    monitor: "Val_loss"


wandb:
  project: "sacyr"
  entity: "inaki"
  dir: "wandb"
  

#output_logger:
#  name: wandb_img_output_errors

