dataset:
  name: CIFAR10
  root: ./data/datasets
  batch_size: 256
  num_workers: 4
model:
  name: resnet18
  weights: ResNet18_Weights.DEFAULT
  num_classes: 10
preprocessing:
- name: to_tensor
loss:
  name: cross_entropy
optimizer:
  name: adam
  lr: 0.01
  weight_decay: 0.0001
  scheduler: step
  step_size: 10
  gamma: 0.1
training:
  epochs: 10
  batch_size: 256
  num_workers: 4
  seed: 42
  device: cuda
scheduler:
  name: reduce_on_plateau
  patience: 2
  factor: 0.1
metrics:
- name: f1_score
  average: weighted
callbacks:
- name: checkpoint
  dirpath: checkpoints/
  monitor: loss
  mode: min
experiment_id: resnet18_bef64961
